# Generated by Django 5.1.1 on 2024-10-31 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('login', models.TextField(db_column='Email', unique=True)),
                ('password', models.TextField(db_column='Password')),
                ('full_name', models.TextField(blank=True, db_column='FirstName', null=True)),
                ('role', models.TextField(db_column='role')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('address', models.TextField()),
                ('delivery_deadline', models.DateField(blank=True, db_column='deadline', null=True)),
            ],
        ),
    ]
