# Generated by Django 5.1.1 on 2024-10-31 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='full_name',
            field=models.TextField(blank=True, db_column='FullName', null=True),
        ),
    ]
