# Generated by Django 5.1.1 on 2024-10-31 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_users_groups_users_is_superuser_users_last_login_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='users',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='users',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='users',
            name='user_permissions',
        ),
    ]
