# Generated by Django 5.1.1 on 2024-10-31 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_remove_users_groups_remove_users_is_superuser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('size', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CakeDecoration',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('article', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('unit_of_measurement', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='images/')),
                ('decoration_type', models.CharField(max_length=100)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('main_supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('article', models.CharField(max_length=100, verbose_name='Артикул')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('unit_of_measure', models.CharField(max_length=50, verbose_name='Единица измерения')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Количество')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение')),
                ('ingredient_type', models.CharField(max_length=100, verbose_name='Тип ингредиента')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Закупочная цена')),
                ('gost', models.CharField(blank=True, max_length=50, null=True, verbose_name='ГОСТ')),
                ('packing', models.CharField(max_length=100, verbose_name='Фасовка')),
                ('characteristic', models.TextField(blank=True, null=True, verbose_name='Характеристика')),
                ('main_supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.supplier', verbose_name='Основной поставщик')),
                ('product', models.ManyToManyField(to='system.product')),
            ],
        ),
    ]
