# Generated by Django 5.1.1 on 2024-10-31 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_product_cakedecoration_ingredient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='product',
        ),
        migrations.CreateModel(
            name='IngredientsSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(db_column='Price', decimal_places=2, max_digits=10)),
                ('ingredient', models.ForeignKey(db_column='ingredient', on_delete=django.db.models.deletion.DO_NOTHING, to='system.ingredient')),
                ('product', models.ForeignKey(db_column='product', on_delete=django.db.models.deletion.DO_NOTHING, to='system.product')),
            ],
            options={
                'db_table': 'amenities_tickets',
            },
        ),
    ]
