# Generated by Django 5.1.1 on 2024-10-31 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_alter_ingredientsspecification_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientsspecification',
            name='quantity',
            field=models.DecimalField(db_column='quantity', decimal_places=2, max_digits=10),
        ),
    ]
