# Generated by Django 5.1.1 on 2024-10-31 21:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_cakedecorationspecification'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Тип оборудования')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('equipment_number', models.CharField(max_length=100, verbose_name='Инвентарный номер')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.equipmenttype', verbose_name='Тип оборудования')),
            ],
        ),
        migrations.CreateModel(
            name='OperationsSpecification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('operation_number', models.CharField(max_length=50, verbose_name='Код операции')),
                ('time_required', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Время на операцию')),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.equipmenttype', verbose_name='Тип оборудования')),
                ('product', models.ForeignKey(db_column='product', on_delete=django.db.models.deletion.DO_NOTHING, to='system.product')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=100, verbose_name='Номер')),
                ('date', models.DateField(blank=True, db_column='date', null=True)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(db_column='price', decimal_places=2, max_digits=10)),
                ('deadline', models.DateField(blank=True, db_column='deadline', null=True)),
                ('examples', models.CharField(max_length=100, verbose_name='Примеры')),
                ('buyer', models.ForeignKey(db_column='buyer', on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders_as_buyer', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(db_column='manager', on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders_as_manager', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(db_column='product', on_delete=django.db.models.deletion.DO_NOTHING, to='system.product')),
            ],
        ),
        migrations.CreateModel(
            name='SemiproductsSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(db_column='quantity', decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(db_column='product', on_delete=django.db.models.deletion.DO_NOTHING, related_name='specification_product', to='system.product')),
                ('semiproduct', models.ForeignKey(db_column='semiproduct', on_delete=django.db.models.deletion.DO_NOTHING, related_name='specification_semiproduct', to='system.product')),
            ],
            options={
                'db_table': 'SemiproductsSpecification',
            },
        ),
    ]
