# Generated by Django 5.1.1 on 2024-11-01 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0010_equipmenttype_equipment_operationsspecification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
