# Generated by Django 5.1.1 on 2024-11-03 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0011_alter_users_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cakedecoration',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Срок годности'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Срок годности'),
        ),
    ]
