# Generated by Django 5.1.1 on 2024-11-10 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0012_cakedecoration_expiry_date_ingredient_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='durability',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='main_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.supplier'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='purchase_date',
            field=models.DateField(blank=True, db_column='purchase_date', null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
