# Generated by Django 5.1.1 on 2024-11-11 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0013_equipment_description_equipment_durability_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapPoint',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение')),
            ],
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='WorkshopMapPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_point', models.ForeignKey(db_column='map_point', on_delete=django.db.models.deletion.CASCADE, to='system.mappoint')),
                ('workshop', models.ForeignKey(db_column='workshop', on_delete=django.db.models.deletion.CASCADE, to='system.workshop')),
            ],
            options={
                'db_table': 'workshop_map_points',
            },
        ),
    ]
