# Generated by Django 5.1.1 on 2024-11-11 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0015_workshop_points'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mappoint',
            table='z_points',
        ),
        migrations.AlterModelTable(
            name='workshop',
            table='z_workshop',
        ),
        migrations.AlterModelTable(
            name='workshopmappoint',
            table='z_workshop_map_points',
        ),
    ]
