# Generated by Django 5.1.1 on 2024-11-11 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0016_alter_mappoint_table_alter_workshop_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopmappoint',
            name='x_axis',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='workshopmappoint',
            name='y_axis',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
