# Generated by Django 5.1.1 on 2024-11-11 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0017_workshopmappoint_x_axis_workshopmappoint_y_axis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopmappoint',
            name='x_axis',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workshopmappoint',
            name='y_axis',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
