# Generated by Django 5.1.1 on 2024-11-11 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0018_alter_workshopmappoint_x_axis_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(db_column='Статус', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='system.status'),
        ),
    ]
