# Generated by Django 5.1.1 on 2024-11-23 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0019_status_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityAssurance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('parameter', models.CharField(max_length=100)),
                ('assured', models.BooleanField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.order')),
            ],
        ),
    ]
