# Generated by Django 5.1.1 on 2024-11-24 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0020_qualityassurance'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualityassurance',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
