# Generated by Django 5.1.1 on 2024-11-26 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0020_qualityassurance'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cakedecorationspecification',
            table='w_CakeDecorationSpecification',
        ),
        migrations.AlterModelTable(
            name='ingredientsspecification',
            table='w_IngredientsSpecification',
        ),
        migrations.AlterModelTable(
            name='product',
            table='w_Product',
        ),
        migrations.AlterModelTable(
            name='semiproductsspecification',
            table='w_SemiproductsSpecification',
        ),
    ]
