# Generated by Django 5.1.1 on 2024-11-29 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0021_alter_cakedecorationspecification_table_and_more'),
        ('system', '0021_qualityassurance_comment'),
    ]

    operations = [
    ]
