# Generated by Django 5.1.1 on 2024-12-01 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0022_merge_20241129_0021'),
        ('system', '0023_alter_qualityassurance_comment'),
    ]

    operations = [
    ]
