# Generated by Django 5.1.1 on 2024-12-01 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0024_merge_20241201_0548'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentProblem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('occur_time', models.DateTimeField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('Equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.equipment')),
            ],
        ),
    ]
